<a href="https://colab.research.google.com/github/KingaPro/data-science-udemy/blob/main/wst%C4%99p.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.__version__

'1.22.4'

In [ ]:
print(dir(np)) # wyświetla wszystkie elementy z biblioteki np

In [ ]:
help(np.array) # wystwietlenie helpa o array

In [7]:
x=np.array([1,3])
x

array([1, 3])

In [8]:
print(x)

[1 3]


In [9]:
type(x)

numpy.ndarray

In [10]:
x.ndim

1

In [11]:
x.size

2

In [12]:
x.dtype

dtype('int64')

In [14]:
np.array([1.5,34.3,6.7])

array([ 1.5, 34.3,  6.7])

In [18]:
x1=np.array([[1,2],[-3,1]]) # tablica z dwoma wymiarami
print(x1)

[[ 1  2]
 [-3  1]]


In [20]:
x1.ndim

2

In [21]:
x1.shape # rozmiar tablicy na 2 na 2

(2, 2)

In [24]:
x3=np.array([[1,23,4],[4,5,3]])
print(x3)

[[ 1 23  4]
 [ 4  5  3]]


In [30]:
x=np.array(
    [[[4,3,2],
     [6,7,8]],

     [[5,8,6],
     [9,9,8]],

     [[4,5,2],
     [5,6,7]]]
)
print(x) # tablica trzywymiarowa

[[[4 3 2]
  [6 7 8]]

 [[5 8 6]
  [9 9 8]]

 [[4 5 2]
  [5 6 7]]]


In [31]:
x.shape # 3 tabele, po 2 wiersze, 3 kolumny

(3, 2, 3)